// VISTA: crea el HTML a partir del estado recibido del modelo.
// Así la interfaz no decide qué productos existen ni cómo se guardan.
const escapeHtml = value => String(value).replace(/[&<>\"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '\"': '&quot;', "'": '&#039;' }[char]));

class DashboardView {
  constructor(model) { this.model = model; }
  // Una tarjeta reutilizable para productos activos y productos de la tienda.
  productCard(product, owned = true) {
    const name = escapeHtml(this.model.getProductName(product));
    return `<article class="dashboard-product-card"><div class="product-card-top"><span class="product-card-icon">${product.icon}</span><span class="status-chip ${owned ? 'status-progress' : 'status-planned'}">${owned ? 'Activo' : product.label}</span></div><h3>${name}</h3><p>${product.description}</p><div class="product-card-footer">${owned ? `<span><strong>${product.saving} h</strong> ahorradas / mes</span><button class="panel-link" type="button" data-rename-product="${product.id}">Editar nombre</button>` : `<strong>$${product.price}<small> / mes</small></strong><button class="btn btn-secondary store-buy" type="button" data-buy-product="${product.id}">Adquirir</button>`}</div></article>`;
  }
  renderProducts() { document.getElementById('products-mount').innerHTML = `<div class="dashboard-section-heading"><div><span class="panel-kicker">Tu catálogo</span><h2 id="products-title">Mis productos</h2><p>Administra el nombre y el estado de las soluciones activas.</p></div><button class="btn btn-secondary" type="button" data-open-view="store">+ Añadir producto</button></div><div class="owned-products-grid">${this.model.ownedProducts.map(product => this.productCard(product)).join('')}</div>`; }
  renderStore(filter = 'all') { const products = this.model.state.catalog.filter(product => filter === 'all' || product.category === filter); document.getElementById('store-mount').innerHTML = `<div class="dashboard-section-heading"><div><span class="panel-kicker">Catálogo TeleCrom</span><h2 id="store-title">Encuentra tu próxima ventaja</h2><p>Adquiere productos digitales y activa nuevas capacidades en minutos.</p></div><span class="store-balance">Crédito disponible <strong>$1,240</strong></span></div><div class="store-filters">${[['all', 'Todos'], ['automation', 'Automatizaciones'], ['security', 'Seguridad'], ['growth', 'Crecimiento']].map(([id, label]) => `<button class="store-filter ${filter === id ? 'active' : ''}" type="button" data-store-filter="${id}">${label}</button>`).join('')}</div><div class="store-grid">${products.map(product => this.productCard(product, this.model.state.products.includes(product.id))).join('')}</div>`; }
  renderAnalytics() { const total = this.model.ownedProducts.reduce((sum, product) => sum + product.saving, 0).toFixed(1); document.getElementById('analytics-mount').innerHTML = `<div class="dashboard-section-heading"><div><span class="panel-kicker">Impacto medible</span><h2 id="analytics-title">Estadísticas de tu operación</h2><p>Una lectura clara de lo que tus productos hacen por tu equipo.</p></div><span class="analytics-period">Últimos 30 días ▾</span></div><div class="analytics-grid"><article class="dashboard-panel analytics-main"><div class="dashboard-panel-heading"><div><span class="panel-kicker">Eficiencia</span><h2>Tiempo recuperado</h2></div><strong class="chart-total">${total} h <small>+24%</small></strong></div><div class="bar-chart"><div class="chart-bar" style="--bar-height:42%"><span>3.2 h</span><i></i><small>Sem 1</small></div><div class="chart-bar" style="--bar-height:63%"><span>4.8 h</span><i></i><small>Sem 2</small></div><div class="chart-bar" style="--bar-height:78%"><span>5.9 h</span><i></i><small>Sem 3</small></div><div class="chart-bar is-current" style="--bar-height:91%"><span>6.8 h</span><i></i><small>Sem 4</small></div></div></article><article class="dashboard-panel impact-list"><div class="dashboard-panel-heading"><div><span class="panel-kicker">Por producto</span><h2>Mayor impacto</h2></div></div>${this.model.ownedProducts.map(product => `<div class="impact-row"><span class="impact-icon">${product.icon}</span><div><strong>${escapeHtml(this.model.getProductName(product))}</strong><small>${product.label}</small></div><b>${product.saving} h</b></div>`).join('')}</article></div><div class="dashboard-panel analytics-footnote"><span class="insight-icon">✦</span><div><strong>Tu automatización está funcionando.</strong><p>Estas herramientas están liberando tiempo para que tu equipo se concentre en crecer.</p></div><button class="panel-link" type="button" data-open-view="store">Ver recomendaciones →</button></div>`; }
  renderAccount() { const account = this.model.state.account; const initials = account.name.split(' ').map(part => part[0]).join('').slice(0, 2).toUpperCase(); document.getElementById('account-mount').innerHTML = `<div class="dashboard-section-heading"><div><span class="panel-kicker">Preferencias</span><h2 id="account-title">Mi cuenta</h2><p>Controla tus datos, seguridad y notificaciones desde aquí.</p></div><span class="account-avatar">${initials}</span></div><div class="account-layout"><form class="dashboard-panel account-form" id="profile-form"><div class="dashboard-panel-heading"><div><span class="panel-kicker">Perfil</span><h2>Información personal</h2></div></div><div class="account-form-grid"><label>Nombre completo<input type="text" name="name" value="${escapeHtml(account.name)}" required></label><label>Correo electrónico<input type="email" name="email" value="${escapeHtml(account.email)}" required></label><label>Empresa<input type="text" name="company" value="${escapeHtml(account.company)}" placeholder="Nombre de tu empresa"></label><label>Zona horaria<select name="timezone"><option>GMT-5 · Bogotá, Lima</option><option>GMT-6 · Ciudad de México</option></select></label></div><div class="account-form-footer"><span class="form-feedback" id="profile-feedback"></span><button class="btn btn-primary" type="submit">Guardar cambios</button></div></form><form class="dashboard-panel account-form" id="password-form"><div class="dashboard-panel-heading"><div><span class="panel-kicker">Seguridad</span><h2>Cambiar contraseña</h2></div></div><label>Contraseña actual<input type="password" name="current" required></label><label>Nueva contraseña<input type="password" name="next" minlength="6" required></label><label>Confirmar nueva contraseña<input type="password" name="confirm" minlength="6" required></label><div class="account-form-footer"><span class="form-feedback" id="password-feedback"></span><button class="btn btn-secondary" type="submit">Actualizar contraseña</button></div></form></div>`; }
}

// Namespace global para permitir abrir dashboard.html directamente desde el explorador.
window.TeleCromDashboardView = DashboardView;
